changelog:
  exclude:
    labels:
      - chore
      - revert
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: 🚀 Features
      labels:
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - fix
    - title: 🧰 Maintenance
      labels:
        - refactor
        - test
        - build
        - ci
    - title: 🛠️ Other Changes
      labels:
        - "*"
