name: "Dependabot: Update bun.lockb 🤖"

on:
  pull_request:
    branches:
      - "dependabot/**"

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  update-bun-lockb:
    name: "Update bun.lockb"
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git config --local user.name 'dependabot[bot]'
          git config --local user.email 'dependabot[bot]@users.noreply.github.com'
          bun install
          git add bun.lockb
          git commit -m 'chore(deps): :arrow_up: update bun.lockb'
          git push
