name: Release Kaggle Plus 🚀

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Archive
        run: |
          mv dist kaggle-plus
          zip -r kaggle-plus.zip kaggle-plus
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: kaggle-plus.zip
          draft: true
          generate_release_notes: true
